#!/usr/bin/env bash
# freeze-heldout.sh — one-time setup that produces the held-out anchor
# transcripts. For each (tool, held-out scenario) pair we run one Claude
# session inside the per-tool docker image and save the transcript under
# bench/scenarios/held-out/transcripts/<tool>/<repo>/.
#
# Frozen transcripts are committed and never re-generated by the
# improvement loop — the loop only re-scores them per iteration to
# anchor `llm_quality` against `gold.json`.
#
# Runs entirely through docker, matching run.sh. The host code path was
# removed on 2026-05-17 when docker became canonical.
set -euo pipefail

BENCH_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT_ROOT="$(cd "$BENCH_DIR/.." && pwd)"
LIB_DIR="$BENCH_DIR/lib"
HELDOUT_DIR="$BENCH_DIR/scenarios/held-out"
TRANSCRIPTS_DIR="$HELDOUT_DIR/transcripts"
# shellcheck disable=SC1091
source "$LIB_DIR/load-env.sh"

MAX_BUDGET_USD="2.00"
SESSION_TIMEOUT=1800   # 30 min — generous for held-out one-shots
DOCKER_TAG="dev"

FILTER_TOOLS="sense,baseline"
FILTER_SCENARIOS=""
DRY_RUN=false
FORCE=false
MODEL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tool) FILTER_TOOLS="$2"; shift 2 ;;
    --scenario) FILTER_SCENARIOS="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --force) FORCE=true; shift ;;
    --budget) MAX_BUDGET_USD="$2"; shift 2 ;;
    --timeout) SESSION_TIMEOUT="$2"; shift 2 ;;
    --model) MODEL="$2"; shift 2 ;;
    --tag) DOCKER_TAG="$2"; shift 2 ;;
    -h|--help)
      cat <<EOF
Usage: freeze-heldout.sh [options]

Freeze held-out transcripts. One-time setup; transcripts are committed
and never re-generated by the improvement loop. Runs in docker.

Options:
  --tool        Comma-separated tool filter (default: sense,baseline)
  --scenario    Comma-separated scenario slug filter (e.g. flask-blueprints)
  --dry-run     Show what would run; do not invoke docker
  --force       Re-freeze even if transcript.json already exists
  --budget USD  Max USD per Claude session (default: $MAX_BUDGET_USD)
  --timeout S   Per-session timeout in seconds (default: $SESSION_TIMEOUT)
  --model M     Claude model (e.g. sonnet, opus)
  --tag TAG     Image tag (default: $DOCKER_TAG)
EOF
      exit 0
      ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

matches_filter() {
  local value="$1" filter="$2"
  [[ -z "$filter" ]] && return 0
  echo "$filter" | tr ',' '\n' | grep -qx "$value"
}

timestamp() { date +%Y-%m-%dT%H:%M:%S; }
log() { echo "[$(timestamp)] $*" >&2; }

ensure_docker_image() {
  local tool="$1"
  local image="bench-${tool}:${DOCKER_TAG}"
  if ! docker image inspect "$image" >/dev/null 2>&1; then
    echo "ERROR: docker image $image not found locally." >&2
    echo "  Build it: docker build -f bench/global/docker/${tool}/Dockerfile -t $image ." >&2
    return 1
  fi
}

# --- Discover held-out scenarios ---

if [[ ! -d "$HELDOUT_DIR" ]]; then
  echo "Held-out scenarios dir missing: $HELDOUT_DIR" >&2
  exit 2
fi

scenarios=()
scenario_repos=()
for scenariofile in "$HELDOUT_DIR"/*.yaml; do
  [[ -f "$scenariofile" ]] || continue
  name="$(basename "$scenariofile" .yaml)"
  [[ "$name" == *.rubric ]] && continue
  repo=$(python3 -c "
import sys,yaml
d=yaml.safe_load(open(sys.argv[1]))
print(d.get('repo', ''))
" "$scenariofile" 2>/dev/null || echo "")
  [[ -z "$repo" ]] && continue
  matches_filter "$name" "$FILTER_SCENARIOS" || continue
  scenarios+=("$name")
  scenario_repos+=("$repo")
done

if [[ ${#scenarios[@]} -eq 0 ]]; then
  echo "No held-out scenarios matched" >&2
  exit 1
fi

IFS=',' read -r -a tools <<< "$FILTER_TOOLS"

total=$(( ${#tools[@]} * ${#scenarios[@]} ))
log "Held-out freeze: ${#tools[@]} tools x ${#scenarios[@]} scenarios = $total transcripts (tag=$DOCKER_TAG)"
log "Tools:     ${tools[*]}"
log "Scenarios: ${scenarios[*]}"

for t in "${tools[@]}"; do ensure_docker_image "$t" || exit 1; done

if $DRY_RUN; then
  echo ""
  echo "=== DRY RUN (bench-<tool>:$DOCKER_TAG) ==="
  echo ""
  n=0
  for tool in "${tools[@]}"; do
    for i in "${!scenarios[@]}"; do
      n=$((n + 1))
      sc="${scenarios[$i]}"
      repo="${scenario_repos[$i]}"
      out="$TRANSCRIPTS_DIR/$tool/$repo/transcript.json"
      exists="(new)"
      [[ -f "$out" ]] && ! $FORCE && exists="(exists, skip)"
      echo "  [$n/$total] tool=$tool scenario=$sc repo=$repo $exists"
    done
  done
  echo ""
  echo "Estimated cost: up to \$$(echo "$total * $MAX_BUDGET_USD" | bc) (ceiling, not actual)"
  exit 0
fi

# --- Main freeze loop ---

n=0
produced=0
skipped=0
failed=0

for tool in "${tools[@]}"; do
  for i in "${!scenarios[@]}"; do
    n=$((n + 1))
    sc="${scenarios[$i]}"
    repo="${scenario_repos[$i]}"
    out_dir="$TRANSCRIPTS_DIR/$tool/$repo"
    out_transcript="$out_dir/transcript.json"

    log "[$n/$total] tool=$tool scenario=$sc repo=$repo"

    if [[ -f "$out_transcript" ]] && ! $FORCE; then
      log "  SKIP: already frozen at $out_transcript (use --force to overwrite)"
      skipped=$((skipped + 1))
      continue
    fi

    mkdir -p "$out_dir"
    image="bench-${tool}:${DOCKER_TAG}"

    docker_args=(
      run --rm
      -e ANTHROPIC_API_KEY
      -e IS_SANDBOX=1
      -v "$out_dir:/out"
      "$image"
      --scenario "$sc"
      --budget "$MAX_BUDGET_USD"
      --timeout "$SESSION_TIMEOUT"
    )
    [[ -n "$MODEL" ]] && docker_args+=(--model "$MODEL")

    log "  docker run $image (budget=\$$MAX_BUDGET_USD timeout=${SESSION_TIMEOUT}s)..."
    docker "${docker_args[@]}" && rc=0 || rc=$?

    # Entrypoint writes /out/run_meta.json. Augment it with held_out=True
    # so downstream code can distinguish frozen transcripts from regular
    # scoring runs without inspecting the path.
    if [[ -f "$out_dir/run_meta.json" ]]; then
      python3 -c "
import json,sys
p=sys.argv[1]
with open(p) as f: m=json.load(f)
m['held_out']=True
with open(p,'w') as f: json.dump(m,f,indent=2); f.write('\n')
" "$out_dir/run_meta.json"
    fi

    if [[ $rc -eq 0 ]]; then
      log "  done"
      produced=$((produced + 1))
    else
      log "  FAIL: docker exit=$rc"
      failed=$((failed + 1))
    fi
  done
done

log ""
log "=== Held-out freeze complete ==="
log "  Total: $total | Produced: $produced | Skipped: $skipped | Failed: $failed"
log "  Transcripts: $TRANSCRIPTS_DIR/"
