package summary

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/luuuc/sense/internal/sqlite"
	"github.com/luuuc/sense/internal/version"
)

const stubSummary = "# Codebase Summary\n\nNo scan data yet. Run `sense scan` to index this codebase.\n"

const DefaultTokenBudget = 8000

const charsPerToken = 4

var (
	gemspecDescRe = regexp.MustCompile(`\.\s*(?:summary|description)\s*=\s*["']([^"']+)["']`)
	pomDescRe     = regexp.MustCompile(`<description>([^<]+)</description>`)
)

func TokenBudget() int {
	if env := os.Getenv("SENSE_SUMMARY_TOKENS"); env != "" {
		if v, err := strconv.Atoi(env); err == nil && v > 0 {
			return v
		}
	}
	return DefaultTokenBudget
}

type section struct {
	title  string
	render func(ctx context.Context, db *sql.DB) (string, error)
}

func Generate(ctx context.Context, adapter *sqlite.Adapter, senseDir, repoRoot string) error {
	db := adapter.DB()
	path := filepath.Join(senseDir, "summary.md")

	var fileCount int
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM sense_files").Scan(&fileCount); err != nil {
		return err
	}
	if fileCount == 0 {
		if err := os.MkdirAll(senseDir, 0o755); err != nil {
			return err
		}
		return os.WriteFile(path, []byte(stubSummary), 0o644)
	}

	budget := TokenBudget() * charsPerToken

	desc := renderProject(repoRoot)
	if desc != "" {
		if err := adapter.WriteMeta(ctx, "project_description", desc); err != nil {
			return err
		}
	}

	sections := []section{
		{"Fingerprint", renderFingerprint},
		{"Project", func(_ context.Context, _ *sql.DB) (string, error) {
			return desc, nil
		}},
		{"Main Areas", renderMainAreas},
		{"Key Abstractions", func(ctx context.Context, _ *sql.DB) (string, error) {
			return renderKeyAbstractions(ctx, adapter)
		}},
		{"Reading Path", renderReadingPath},
		{"Known Noise", renderKnownNoise},
	}

	var parts []string
	header := fmt.Sprintf("<!-- generated by sense %s at %s -->\n# Codebase Summary\n",
		version.Version, time.Now().UTC().Format(time.RFC3339))
	used := len(header)
	parts = append(parts, header)

	var omitted []string
	for i, s := range sections {
		body, err := s.render(ctx, db)
		if err != nil || body == "" {
			continue
		}
		block := fmt.Sprintf("\n## %s\n\n%s\n", s.title, body)
		if used+len(block) > budget {
			remaining := budget - used
			if remaining > 80 {
				block = block[:remaining-20] + "\n\n*(truncated)*\n"
				parts = append(parts, block)
			}
			omitted = append(omitted, s.title)
			for _, s2 := range sections[i+1:] {
				omitted = append(omitted, s2.title)
			}
			break
		}
		parts = append(parts, block)
		used += len(block)
	}

	if len(omitted) > 0 {
		footer := fmt.Sprintf("\n---\n*Omitted sections (use Sense tools for details): %s*\n",
			strings.Join(omitted, ", "))
		parts = append(parts, footer)
	}

	content := strings.Join(parts, "")
	return os.WriteFile(path, []byte(content), 0o644)
}

func renderFingerprint(ctx context.Context, db *sql.DB) (string, error) {
	var files, symbols, edges int
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM sense_files").Scan(&files); err != nil {
		return "", err
	}
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM sense_symbols").Scan(&symbols); err != nil {
		return "", err
	}
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM sense_edges").Scan(&edges); err != nil {
		return "", err
	}

	langs, err := queryLanguages(ctx, db)
	if err != nil {
		return "", err
	}

	sort.Slice(langs, func(i, j int) bool { return langs[i].symbols > langs[j].symbols })

	primary := ""
	if len(langs) > 0 {
		primary = langs[0].name
	}

	frameworks := queryFrameworks(ctx, db)

	var b strings.Builder
	fmt.Fprintf(&b, "%s project", capitalize(primary))
	if len(frameworks) > 0 {
		fmt.Fprintf(&b, " (%s)", strings.Join(frameworks, ", "))
	}
	fmt.Fprintf(&b, ". %d files, %d symbols, %d edges.", files, symbols, edges)

	if len(langs) > 1 {
		langStrs := make([]string, len(langs))
		for i, l := range langs {
			langStrs[i] = fmt.Sprintf("%s (%d)", l.name, l.symbols)
		}
		fmt.Fprintf(&b, "\nLanguages: %s.", strings.Join(langStrs, ", "))
	}

	return b.String(), nil
}

const (
	maxReadmeBytes = 64 * 1024
	maxReadmeLines = 200
	maxDescBytes   = 300
)

func readStructuredDescription(repoRoot string) string {
	// package.json
	if data, err := os.ReadFile(filepath.Join(repoRoot, "package.json")); err == nil {
		var pkg map[string]interface{}
		if err := json.Unmarshal(data, &pkg); err == nil {
			if desc, ok := pkg["description"].(string); ok && desc != "" {
				if len(desc) > maxDescBytes {
					return truncateUTF8(desc, maxDescBytes-3) + "..."
				}
				return desc
			}
		}
	}

	// Cargo.toml
	if desc := scanTOMLValue(filepath.Join(repoRoot, "Cargo.toml"), "[package]", "description"); desc != "" {
		return desc
	}

	// pyproject.toml
	if desc := scanTOMLValue(filepath.Join(repoRoot, "pyproject.toml"), "[project]", "description"); desc != "" {
		return desc
	}

	// setup.cfg
	if desc := scanINIValue(filepath.Join(repoRoot, "setup.cfg"), "metadata", "description"); desc != "" {
		return desc
	}

	// *.gemspec
	if matches, _ := filepath.Glob(filepath.Join(repoRoot, "*.gemspec")); len(matches) > 0 {
		if data, err := os.ReadFile(matches[0]); err == nil {
			if m := gemspecDescRe.FindSubmatch(data); m != nil {
				return string(m[1])
			}
		}
	}

	// pom.xml
	if data, err := os.ReadFile(filepath.Join(repoRoot, "pom.xml")); err == nil {
		if m := pomDescRe.FindSubmatch(data); m != nil {
			return string(m[1])
		}
	}

	return ""
}

func scanTOMLValue(path, section, key string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	lines := strings.Split(string(data), "\n")
	inSection := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == section {
			inSection = true
			continue
		}
		if inSection && strings.HasPrefix(trimmed, "[") {
			break
		}
		if inSection {
			prefix := key + " = "
			if strings.HasPrefix(trimmed, prefix) {
				val := strings.TrimSpace(strings.TrimPrefix(trimmed, prefix))
				val = strings.Trim(val, `"`)
				val = strings.Trim(val, `'`)  
				if len(val) > maxDescBytes {
					val = truncateUTF8(val, maxDescBytes-3) + "..."
				}
				return val
			}
		}
	}
	return ""
}

func scanINIValue(path, section, key string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	lines := strings.Split(string(data), "\n")
	inSection := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "["+section+"]" {
			inSection = true
			continue
		}
		if inSection && strings.HasPrefix(trimmed, "[") {
			break
		}
		if inSection {
			prefix := key + " = "
			if strings.HasPrefix(trimmed, prefix) {
				val := strings.TrimSpace(strings.TrimPrefix(trimmed, prefix))
				if len(val) > maxDescBytes {
					val = truncateUTF8(val, maxDescBytes-3) + "..."
				}
				return val
			}
		}
	}
	return ""
}

func renderProject(repoRoot string) string {
	if repoRoot == "" {
		return ""
	}
	if desc := readStructuredDescription(repoRoot); desc != "" {
		return desc
	}
	f, err := os.Open(filepath.Join(repoRoot, "README.md"))
	if err != nil {
		return ""
	}
	defer func() { _ = f.Close() }()
	data, err := io.ReadAll(io.LimitReader(f, maxReadmeBytes))
	if err != nil {
		return ""
	}
	lines := strings.SplitN(string(data), "\n", maxReadmeLines+1)
	if len(lines) > maxReadmeLines {
		lines = lines[:maxReadmeLines]
	}

	var para []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			if len(para) > 0 {
				break
			}
			continue
		}
		if strings.HasPrefix(trimmed, "[![") || strings.HasPrefix(trimmed, "![") ||
			strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, "<") {
			if len(para) > 0 {
				break
			}
			continue
		}
		para = append(para, trimmed)
	}
	if len(para) == 0 {
		return ""
	}
	desc := strings.Join(para, " ")
	if len(desc) > maxDescBytes {
		desc = truncateUTF8(desc, maxDescBytes-3) + "..."
	}
	return desc
}

func truncateUTF8(s string, maxBytes int) string {
	if len(s) <= maxBytes {
		return s
	}
	for maxBytes > 0 && !utf8.RuneStart(s[maxBytes]) {
		maxBytes--
	}
	return s[:maxBytes]
}

func renderMainAreas(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `SELECT f.path, s.kind, COUNT(s.id)
		FROM sense_files f
		JOIN sense_symbols s ON s.file_id = f.id
		GROUP BY f.path, s.kind`)
	if err != nil {
		return "", err
	}
	defer func() { _ = rows.Close() }()

	type nsData struct {
		total int
		kinds map[string]int
	}
	areas := make(map[string]*nsData)
	for rows.Next() {
		var fpath, kind string
		var n int
		if err := rows.Scan(&fpath, &kind, &n); err != nil {
			return "", err
		}
		ns := namespacePrefixFromPath(fpath)
		d, ok := areas[ns]
		if !ok {
			d = &nsData{kinds: make(map[string]int)}
			areas[ns] = d
		}
		d.total += n
		d.kinds[kind] += n
	}
	if err := rows.Err(); err != nil {
		return "", err
	}

	type nsEntry struct {
		name    string
		symbols int
		desc    string
	}
	entries := make([]nsEntry, 0, len(areas))
	for name, d := range areas {
		entries = append(entries, nsEntry{name, d.total, dominantKindDesc(d.kinds)})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].symbols > entries[j].symbols })

	if len(entries) > 8 {
		entries = entries[:8]
	}

	var b strings.Builder
	b.WriteString("*Explore any area: `sense_conventions domain=\"...\"` or `sense_search query=\"...\"`*\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "- `%s/` — %s (%d symbols)\n", e.name, e.desc, e.symbols)
	}
	return b.String(), nil
}

func dominantKindDesc(kinds map[string]int) string {
	if len(kinds) == 0 {
		return "code"
	}
	best := ""
	bestN := 0
	for k, n := range kinds {
		if n > bestN {
			best = k
			bestN = n
		}
	}
	switch best {
	case "function":
		return "functions"
	case "method":
		return "methods"
	case "class":
		return "classes"
	case "module":
		return "modules"
	case "type":
		return "types"
	case "interface":
		return "interfaces"
	case "constant":
		return "constants"
	default:
		return best + "s"
	}
}

func renderKeyAbstractions(ctx context.Context, adapter *sqlite.Adapter) (string, error) {
	results, err := adapter.TopSymbolsByReach(ctx, "", 8)
	if err != nil {
		return "", err
	}
	if len(results) == 0 {
		return "", nil
	}

	var b strings.Builder
	b.WriteString("*Drill into any symbol: `sense_graph symbol=\"...\"` or `sense_blast symbol=\"...\"`*\n")
	for _, ks := range results {
		if ks.Snippet != "" {
			fmt.Fprintf(&b, "- `%s` (%s) — %d file refs — `%s`\n", ks.Qualified, ks.Kind, ks.RefFiles, ks.Snippet)
		} else {
			fmt.Fprintf(&b, "- `%s` (%s) — %d file refs\n", ks.Qualified, ks.Kind, ks.RefFiles)
		}
	}
	return b.String(), nil
}

func renderReadingPath(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `SELECT s.name, f.path
		FROM sense_symbols s
		JOIN sense_files f ON f.id = s.file_id
		WHERE s.name IN ('main', 'Main') AND s.kind = 'function'
		  AND f.path NOT LIKE '%testdata%'
		  AND f.path NOT LIKE '%fixture%'
		  AND f.path NOT LIKE '%example%'
		LIMIT 5`)
	if err != nil {
		return "", err
	}
	defer func() { _ = rows.Close() }()

	var entries []string
	idx := 1
	for rows.Next() {
		var name, file string
		if err := rows.Scan(&name, &file); err != nil {
			return "", err
		}
		entries = append(entries, fmt.Sprintf("%d. `%s` — %s entry", idx, file, name))
		idx++
	}
	if err := rows.Err(); err != nil {
		return "", err
	}
	if len(entries) == 0 {
		return "", nil
	}
	entries = append(entries, "\n*Next: `sense_search query=\"entry point\"` or `sense_conventions` for project patterns*")
	return strings.Join(entries, "\n") + "\n", nil
}

func renderKnownNoise(ctx context.Context, db *sql.DB) (string, error) {
	noisePatterns := []struct {
		like string
		desc string
	}{
		{"%testdata%", "contains test fixture code; ignore for architecture"},
		{"%fixture%", "contains test fixtures; ignore for architecture"},
		{"%vendor%", "vendored dependencies; ignore for architecture"},
		{"%generated%", "generated code; ignore for architecture"},
		{"%example%", "example code; not part of core architecture"},
	}

	seen := make(map[string]bool)
	var b strings.Builder
	for _, p := range noisePatterns {
		var count int
		err := db.QueryRowContext(ctx,
			`SELECT COUNT(DISTINCT f.path) FROM sense_files f WHERE f.path LIKE ?`, p.like).Scan(&count)
		if err != nil {
			return "", err
		}
		if count > 0 {
			prefix := longestNoisePrefix(ctx, db, p.like)
			if seen[prefix] {
				continue
			}
			seen[prefix] = true
			fmt.Fprintf(&b, "- `%s` — %s (%d files)\n", prefix, p.desc, count)
		}
	}
	return b.String(), nil
}

func longestNoisePrefix(ctx context.Context, db *sql.DB, like string) string {
	fallback := strings.Trim(like, "%")
	rows, err := db.QueryContext(ctx,
		`SELECT f.path FROM sense_files f WHERE f.path LIKE ? ORDER BY f.path LIMIT 20`, like)
	if err != nil {
		return fallback
	}
	defer func() { _ = rows.Close() }()

	var paths []string
	for rows.Next() {
		var p string
		if err := rows.Scan(&p); err != nil {
			continue
		}
		paths = append(paths, filepath.Dir(p))
	}
	if err := rows.Err(); err != nil || len(paths) == 0 {
		return fallback
	}

	prefix := paths[0]
	for _, p := range paths[1:] {
		prefix = commonPrefix(prefix, p)
	}
	if prefix == "" || prefix == "." {
		return fallback
	}
	return prefix + "/"
}

type langEntry struct {
	name    string
	symbols int
}

func queryLanguages(ctx context.Context, db *sql.DB) ([]langEntry, error) {
	rows, err := db.QueryContext(ctx, `SELECT f.language, COUNT(s.id)
		FROM sense_files f
		JOIN sense_symbols s ON s.file_id = f.id
		WHERE f.language != ''
		GROUP BY f.language
		ORDER BY COUNT(s.id) DESC`)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var out []langEntry
	for rows.Next() {
		var lang string
		var n int
		if err := rows.Scan(&lang, &n); err != nil {
			return nil, err
		}
		out = append(out, langEntry{lang, n})
	}
	return out, rows.Err()
}

func queryFrameworks(ctx context.Context, db *sql.DB) []string {
	var val string
	err := db.QueryRowContext(ctx, `SELECT value FROM sense_meta WHERE key = 'frameworks'`).Scan(&val)
	if err != nil || val == "" {
		return nil
	}
	var out []string
	if err := json.Unmarshal([]byte(val), &out); err != nil {
		return nil
	}
	return out
}

func namespacePrefixFromPath(p string) string {
	first, rest, ok := strings.Cut(p, "/")
	if !ok {
		return "."
	}
	if second, _, ok := strings.Cut(rest, "/"); ok {
		return first + "/" + second
	}
	return first
}

func commonPrefix(a, b string) string {
	i := 0
	for i < len(a) && i < len(b) && a[i] == b[i] {
		i++
	}
	s := a[:i]
	if last := strings.LastIndex(s, "/"); last >= 0 {
		return s[:last]
	}
	return s
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
