package summary

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/luuuc/sense/internal/version"
)

const stubSummary = "# Codebase Summary\n\nNo scan data yet. Run `sense scan` to index this codebase.\n"

const DefaultTokenBudget = 8000

const charsPerToken = 4

func TokenBudget() int {
	if env := os.Getenv("SENSE_SUMMARY_TOKENS"); env != "" {
		if v, err := strconv.Atoi(env); err == nil && v > 0 {
			return v
		}
	}
	return DefaultTokenBudget
}

type section struct {
	title  string
	render func(ctx context.Context, db *sql.DB) (string, error)
}

func Generate(ctx context.Context, db *sql.DB, senseDir string) error {
	path := filepath.Join(senseDir, "summary.md")

	var fileCount int
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM sense_files").Scan(&fileCount); err != nil {
		return err
	}
	if fileCount == 0 {
		if err := os.MkdirAll(senseDir, 0o755); err != nil {
			return err
		}
		return os.WriteFile(path, []byte(stubSummary), 0o644)
	}

	budget := TokenBudget() * charsPerToken

	sections := []section{
		{"Fingerprint", renderFingerprint},
		{"Main Areas", renderMainAreas},
		{"Key Abstractions", renderKeyAbstractions},
		{"Reading Path", renderReadingPath},
		{"Known Noise", renderKnownNoise},
	}

	var parts []string
	header := fmt.Sprintf("<!-- generated by sense %s at %s -->\n# Codebase Summary\n",
		version.Version, time.Now().UTC().Format(time.RFC3339))
	used := len(header)
	parts = append(parts, header)

	var omitted []string
	for i, s := range sections {
		body, err := s.render(ctx, db)
		if err != nil || body == "" {
			continue
		}
		block := fmt.Sprintf("\n## %s\n\n%s\n", s.title, body)
		if used+len(block) > budget {
			remaining := budget - used
			if remaining > 80 {
				block = block[:remaining-20] + "\n\n*(truncated)*\n"
				parts = append(parts, block)
			}
			omitted = append(omitted, s.title)
			for _, s2 := range sections[i+1:] {
				omitted = append(omitted, s2.title)
			}
			break
		}
		parts = append(parts, block)
		used += len(block)
	}

	if len(omitted) > 0 {
		footer := fmt.Sprintf("\n---\n*Omitted sections (use Sense tools for details): %s*\n",
			strings.Join(omitted, ", "))
		parts = append(parts, footer)
	}

	content := strings.Join(parts, "")
	return os.WriteFile(path, []byte(content), 0o644)
}

func renderFingerprint(ctx context.Context, db *sql.DB) (string, error) {
	var files, symbols, edges int
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM sense_files").Scan(&files); err != nil {
		return "", err
	}
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM sense_symbols").Scan(&symbols); err != nil {
		return "", err
	}
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM sense_edges").Scan(&edges); err != nil {
		return "", err
	}

	langs, err := queryLanguages(ctx, db)
	if err != nil {
		return "", err
	}

	sort.Slice(langs, func(i, j int) bool { return langs[i].symbols > langs[j].symbols })

	primary := ""
	if len(langs) > 0 {
		primary = langs[0].name
	}

	frameworks := queryFrameworks(ctx, db)

	var b strings.Builder
	fmt.Fprintf(&b, "%s project", capitalize(primary))
	if len(frameworks) > 0 {
		fmt.Fprintf(&b, " (%s)", strings.Join(frameworks, ", "))
	}
	fmt.Fprintf(&b, ". %d files, %d symbols, %d edges.", files, symbols, edges)

	if len(langs) > 1 {
		langStrs := make([]string, len(langs))
		for i, l := range langs {
			langStrs[i] = fmt.Sprintf("%s (%d)", l.name, l.symbols)
		}
		fmt.Fprintf(&b, "\nLanguages: %s.", strings.Join(langStrs, ", "))
	}

	return b.String(), nil
}

func renderMainAreas(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `SELECT f.path, s.kind, COUNT(s.id)
		FROM sense_files f
		JOIN sense_symbols s ON s.file_id = f.id
		GROUP BY f.path, s.kind`)
	if err != nil {
		return "", err
	}
	defer func() { _ = rows.Close() }()

	type nsData struct {
		total int
		kinds map[string]int
	}
	areas := make(map[string]*nsData)
	for rows.Next() {
		var fpath, kind string
		var n int
		if err := rows.Scan(&fpath, &kind, &n); err != nil {
			return "", err
		}
		ns := namespacePrefixFromPath(fpath)
		d, ok := areas[ns]
		if !ok {
			d = &nsData{kinds: make(map[string]int)}
			areas[ns] = d
		}
		d.total += n
		d.kinds[kind] += n
	}
	if err := rows.Err(); err != nil {
		return "", err
	}

	type nsEntry struct {
		name    string
		symbols int
		desc    string
	}
	entries := make([]nsEntry, 0, len(areas))
	for name, d := range areas {
		entries = append(entries, nsEntry{name, d.total, dominantKindDesc(d.kinds)})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].symbols > entries[j].symbols })

	if len(entries) > 8 {
		entries = entries[:8]
	}

	var b strings.Builder
	for _, e := range entries {
		fmt.Fprintf(&b, "- `%s/` — %s (%d symbols)\n", e.name, e.desc, e.symbols)
		fmt.Fprintf(&b, "  Next: `sense_conventions domain=\"%s\"` or `sense_search query=\"%s\"`\n", e.name, e.name)
	}
	return b.String(), nil
}

func dominantKindDesc(kinds map[string]int) string {
	if len(kinds) == 0 {
		return "code"
	}
	best := ""
	bestN := 0
	for k, n := range kinds {
		if n > bestN {
			best = k
			bestN = n
		}
	}
	switch best {
	case "function":
		return "functions"
	case "method":
		return "methods and types"
	case "class":
		return "classes"
	case "module":
		return "modules"
	case "type":
		return "types"
	case "interface":
		return "interfaces"
	case "constant":
		return "constants"
	default:
		return best + "s"
	}
}

var utilitySymbols = map[string]bool{
	"Close": true, "Error": true, "String": true, "make": true,
	"len": true, "append": true, "New": true, "init": true,
	"Format": true, "Write": true, "Read": true, "Reset": true,
	"MarshalJSON": true, "UnmarshalJSON": true,
}

func renderKeyAbstractions(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `SELECT s.qualified, s.name, COUNT(e.id) AS in_degree, s.kind, f.path
		FROM sense_symbols s
		JOIN sense_edges e ON e.target_id = s.id
		JOIN sense_files f ON f.id = s.file_id
		WHERE f.path NOT LIKE '%testdata%'
		  AND f.path NOT LIKE '%fixture%'
		  AND f.path NOT LIKE '%vendor%'
		GROUP BY s.id
		ORDER BY in_degree DESC
		LIMIT 30`)
	if err != nil {
		return "", err
	}
	defer func() { _ = rows.Close() }()

	var b strings.Builder
	n := 0
	for rows.Next() && n < 8 {
		var qualified, name, kind, fpath string
		var callers int
		if err := rows.Scan(&qualified, &name, &callers, &kind, &fpath); err != nil {
			return "", err
		}
		if utilitySymbols[name] {
			continue
		}
		fmt.Fprintf(&b, "- `%s` (%s) — %d incoming edges\n", qualified, kind, callers)
		fmt.Fprintf(&b, "  Next: `sense_graph symbol=\"%s\"` or `sense_blast symbol=\"%s\"`\n", qualified, qualified)
		n++
	}
	if b.Len() == 0 {
		return "", nil
	}
	return b.String(), rows.Err()
}

func renderReadingPath(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `SELECT s.name, f.path
		FROM sense_symbols s
		JOIN sense_files f ON f.id = s.file_id
		WHERE s.name IN ('main', 'Main') AND s.kind = 'function'
		  AND f.path NOT LIKE '%testdata%'
		  AND f.path NOT LIKE '%fixture%'
		  AND f.path NOT LIKE '%example%'
		LIMIT 3`)
	if err != nil {
		return "", err
	}
	defer func() { _ = rows.Close() }()

	var entries []string
	for rows.Next() {
		var name, file string
		if err := rows.Scan(&name, &file); err != nil {
			return "", err
		}
		entries = append(entries, fmt.Sprintf("1. `%s` — %s entry", file, name))
	}
	if err := rows.Err(); err != nil {
		return "", err
	}

	nsRows, err := db.QueryContext(ctx, `SELECT f.path, COUNT(s.id) AS cnt
		FROM sense_files f
		JOIN sense_symbols s ON s.file_id = f.id
		WHERE f.path NOT LIKE '%testdata%'
		  AND f.path NOT LIKE '%fixture%'
		  AND f.path NOT LIKE '%test%'
		GROUP BY f.path`)
	if err != nil {
		return "", err
	}
	defer func() { _ = nsRows.Close() }()

	nsCounts := make(map[string]int)
	for nsRows.Next() {
		var fpath string
		var n int
		if err := nsRows.Scan(&fpath, &n); err != nil {
			return "", err
		}
		ns := namespacePrefixFromPath(fpath)
		nsCounts[ns] += n
	}
	if err := nsRows.Err(); err != nil {
		return "", err
	}

	type nsEntry struct {
		name string
		syms int
	}
	var nsList []nsEntry
	for name, syms := range nsCounts {
		nsList = append(nsList, nsEntry{name, syms})
	}
	sort.Slice(nsList, func(i, j int) bool { return nsList[i].syms > nsList[j].syms })
	if len(nsList) > 4 {
		nsList = nsList[:4]
	}

	idx := len(entries) + 1
	for _, ns := range nsList {
		entries = append(entries, fmt.Sprintf("%d. `%s/` — %d symbols", idx, ns.name, ns.syms))
		idx++
	}

	if len(entries) == 0 {
		return "", nil
	}
	entries = append(entries, "\nNext: `sense_search query=\"entry point\"` or `sense_conventions` for project patterns")
	return strings.Join(entries, "\n") + "\n", nil
}

func renderKnownNoise(ctx context.Context, db *sql.DB) (string, error) {
	noisePatterns := []struct {
		like string
		desc string
	}{
		{"%testdata%", "contains test fixture code; ignore for architecture"},
		{"%fixture%", "contains test fixtures; ignore for architecture"},
		{"%vendor%", "vendored dependencies; ignore for architecture"},
		{"%generated%", "generated code; ignore for architecture"},
		{"%example%", "example code; not part of core architecture"},
	}

	seen := make(map[string]bool)
	var b strings.Builder
	for _, p := range noisePatterns {
		var count int
		err := db.QueryRowContext(ctx,
			`SELECT COUNT(DISTINCT f.path) FROM sense_files f WHERE f.path LIKE ?`, p.like).Scan(&count)
		if err != nil {
			return "", err
		}
		if count > 0 {
			prefix := longestNoisePrefix(ctx, db, p.like)
			if seen[prefix] {
				continue
			}
			seen[prefix] = true
			fmt.Fprintf(&b, "- `%s` — %s (%d files)\n", prefix, p.desc, count)
		}
	}
	return b.String(), nil
}

func longestNoisePrefix(ctx context.Context, db *sql.DB, like string) string {
	rows, err := db.QueryContext(ctx,
		`SELECT f.path FROM sense_files f WHERE f.path LIKE ? LIMIT 20`, like)
	if err != nil {
		return strings.Trim(like, "%")
	}
	defer func() { _ = rows.Close() }()

	var paths []string
	for rows.Next() {
		var p string
		if err := rows.Scan(&p); err != nil {
			continue
		}
		paths = append(paths, filepath.Dir(p))
	}
	if len(paths) == 0 {
		return strings.Trim(like, "%")
	}

	prefix := paths[0]
	for _, p := range paths[1:] {
		prefix = commonPrefix(prefix, p)
	}
	if prefix == "" || prefix == "." {
		return strings.Trim(like, "%")
	}
	return prefix + "/"
}

type langEntry struct {
	name    string
	symbols int
}

func queryLanguages(ctx context.Context, db *sql.DB) ([]langEntry, error) {
	rows, err := db.QueryContext(ctx, `SELECT f.language, COUNT(s.id)
		FROM sense_files f
		JOIN sense_symbols s ON s.file_id = f.id
		WHERE f.language != ''
		GROUP BY f.language
		ORDER BY COUNT(s.id) DESC`)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var out []langEntry
	for rows.Next() {
		var lang string
		var n int
		if err := rows.Scan(&lang, &n); err != nil {
			return nil, err
		}
		out = append(out, langEntry{lang, n})
	}
	return out, rows.Err()
}

func queryFrameworks(ctx context.Context, db *sql.DB) []string {
	var val string
	err := db.QueryRowContext(ctx, `SELECT value FROM sense_meta WHERE key = 'frameworks'`).Scan(&val)
	if err != nil || val == "" {
		return nil
	}
	var out []string
	if err := json.Unmarshal([]byte(val), &out); err != nil {
		return nil
	}
	return out
}

func namespacePrefixFromPath(p string) string {
	first, rest, ok := strings.Cut(p, "/")
	if !ok {
		return "."
	}
	if second, _, ok := strings.Cut(rest, "/"); ok {
		return first + "/" + second
	}
	return first
}

func commonPrefix(a, b string) string {
	i := 0
	for i < len(a) && i < len(b) && a[i] == b[i] {
		i++
	}
	s := a[:i]
	if last := strings.LastIndex(s, "/"); last >= 0 {
		return s[:last]
	}
	return s
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
