package summary_test

import (
	"bytes"
	"context"
	"database/sql"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	_ "modernc.org/sqlite"

	"github.com/luuuc/sense/internal/scan"
	"github.com/luuuc/sense/internal/sqlite"
	"github.com/luuuc/sense/internal/summary"
)

func TestGenerateCreatesSummaryFile(t *testing.T) {
	root := t.TempDir()

	writeFile(t, filepath.Join(root, "main.go"), `package main

func main() {}

func helper() int { return 42 }
`)
	writeFile(t, filepath.Join(root, "util.go"), `package main

type Config struct{}

func NewConfig() Config { return Config{} }
`)

	ctx := context.Background()
	if _, err := scan.Run(ctx, scan.Options{
		Root:     root,
		Output:   &bytes.Buffer{},
		Warnings: io.Discard,
	}); err != nil {
		t.Fatalf("scan.Run: %v", err)
	}

	senseDir := filepath.Join(root, ".sense")
	path := filepath.Join(senseDir, "summary.md")

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("summary.md not created: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "# Codebase Summary") {
		t.Error("missing header")
	}
	if !strings.Contains(content, "Project Fingerprint") {
		t.Error("missing fingerprint section")
	}
	if !strings.Contains(content, "generated by sense") {
		t.Error("missing generated_at header")
	}
}

func TestGenerateRespectsTokenBudget(t *testing.T) {
	root := t.TempDir()

	writeFile(t, filepath.Join(root, "main.go"), `package main

func main() {}
func a() {}
func b() {}
func c() {}
func d() {}
`)

	ctx := context.Background()
	if _, err := scan.Run(ctx, scan.Options{
		Root:     root,
		Output:   &bytes.Buffer{},
		Warnings: io.Discard,
	}); err != nil {
		t.Fatalf("scan.Run: %v", err)
	}

	senseDir := filepath.Join(root, ".sense")
	dbPath := filepath.Join(senseDir, "index.db")

	adapter, err := sqlite.Open(ctx, dbPath)
	if err != nil {
		t.Fatalf("sqlite.Open: %v", err)
	}
	t.Cleanup(func() { _ = adapter.Close() })

	db, err := sql.Open("sqlite", "file:"+dbPath)
	if err != nil {
		t.Fatalf("sql.Open: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })

	t.Setenv("SENSE_SUMMARY_TOKENS", "200")

	outDir := t.TempDir()
	if err := summary.Generate(ctx, db, outDir); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "summary.md"))
	if err != nil {
		t.Fatalf("read summary: %v", err)
	}

	charBudget := 200 * 4
	if len(data) > charBudget+200 {
		t.Errorf("summary too large: %d chars, budget was %d tokens (%d chars)",
			len(data), 200, charBudget)
	}
}

func TestGenerateWritesStubWhenEmpty(t *testing.T) {
	ctx := context.Background()
	senseDir := t.TempDir()
	dbPath := filepath.Join(senseDir, "index.db")

	adapter, err := sqlite.Open(ctx, dbPath)
	if err != nil {
		t.Fatalf("sqlite.Open: %v", err)
	}
	_ = adapter.Close()

	db, err := sql.Open("sqlite", "file:"+dbPath)
	if err != nil {
		t.Fatalf("sql.Open: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })

	outDir := t.TempDir()
	if err := summary.Generate(ctx, db, outDir); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "summary.md"))
	if err != nil {
		t.Fatalf("stub summary.md not created: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "No scan data yet") {
		t.Errorf("expected stub message, got: %s", content)
	}
	if !strings.Contains(content, "sense scan") {
		t.Errorf("expected scan instruction, got: %s", content)
	}
}

func TestTokenBudgetEnvVar(t *testing.T) {
	t.Setenv("SENSE_SUMMARY_TOKENS", "4000")
	if got := summary.TokenBudget(); got != 4000 {
		t.Errorf("TokenBudget() = %d, want 4000", got)
	}
}

func TestTokenBudgetDefault(t *testing.T) {
	t.Setenv("SENSE_SUMMARY_TOKENS", "")
	if got := summary.TokenBudget(); got != summary.DefaultTokenBudget {
		t.Errorf("TokenBudget() = %d, want %d", got, summary.DefaultTokenBudget)
	}
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
}
