package summary

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/luuuc/sense/internal/conventions"
	"github.com/luuuc/sense/internal/version"
)

const DefaultTokenBudget = 8000

const charsPerToken = 4

func TokenBudget() int {
	if env := os.Getenv("SENSE_SUMMARY_TOKENS"); env != "" {
		if v, err := strconv.Atoi(env); err == nil && v > 0 {
			return v
		}
	}
	return DefaultTokenBudget
}

type section struct {
	title  string
	render func(ctx context.Context, db *sql.DB) (string, error)
}

func Generate(ctx context.Context, db *sql.DB, senseDir string) error {
	var fileCount int
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM sense_files").Scan(&fileCount); err != nil {
		return err
	}
	if fileCount == 0 {
		return nil
	}

	budget := TokenBudget() * charsPerToken

	sections := []section{
		{"Project Fingerprint", renderFingerprint},
		{"Top Namespaces", renderTopNamespaces},
		{"Hub Symbols", renderHubSymbols},
		{"Entry Points", renderEntryPoints},
		{"Conventions", renderConventions},
	}

	var parts []string
	header := fmt.Sprintf("<!-- generated by sense %s at %s -->\n# Codebase Summary\n",
		version.Version, time.Now().UTC().Format(time.RFC3339))
	used := len(header)
	parts = append(parts, header)

	var omitted []string
	for i, s := range sections {
		body, err := s.render(ctx, db)
		if err != nil || body == "" {
			continue
		}
		block := fmt.Sprintf("\n## %s\n\n%s\n", s.title, body)
		if used+len(block) > budget {
			remaining := budget - used
			if remaining > 80 {
				block = block[:remaining-20] + "\n\n*(truncated)*\n"
				parts = append(parts, block)
			}
			omitted = append(omitted, s.title)
			for _, s2 := range sections[i+1:] {
				omitted = append(omitted, s2.title)
			}
			break
		}
		parts = append(parts, block)
		used += len(block)
	}

	if len(omitted) > 0 {
		footer := fmt.Sprintf("\n---\n*Omitted sections (use Sense tools for details): %s*\n",
			strings.Join(omitted, ", "))
		parts = append(parts, footer)
	}

	content := strings.Join(parts, "")
	path := filepath.Join(senseDir, "summary.md")
	return os.WriteFile(path, []byte(content), 0o644)
}

func renderFingerprint(ctx context.Context, db *sql.DB) (string, error) {
	var files, symbols, edges int
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM sense_files").Scan(&files); err != nil {
		return "", err
	}
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM sense_symbols").Scan(&symbols); err != nil {
		return "", err
	}
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM sense_edges").Scan(&edges); err != nil {
		return "", err
	}

	langs, err := queryLanguages(ctx, db)
	if err != nil {
		return "", err
	}

	sort.Slice(langs, func(i, j int) bool { return langs[i].symbols > langs[j].symbols })

	primary := ""
	if len(langs) > 0 {
		primary = langs[0].name
	}

	frameworks := queryFrameworks(ctx, db)

	var b strings.Builder
	fmt.Fprintf(&b, "%s project", capitalize(primary))
	if len(frameworks) > 0 {
		fmt.Fprintf(&b, " (%s)", strings.Join(frameworks, ", "))
	}
	fmt.Fprintf(&b, ". %d files, %d symbols, %d edges.", files, symbols, edges)

	if len(langs) > 1 {
		langStrs := make([]string, len(langs))
		for i, l := range langs {
			langStrs[i] = fmt.Sprintf("%s (%d)", l.name, l.symbols)
		}
		fmt.Fprintf(&b, "\nLanguages: %s.", strings.Join(langStrs, ", "))
	}

	return b.String(), nil
}

func renderTopNamespaces(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `SELECT f.path, COUNT(s.id)
		FROM sense_files f
		JOIN sense_symbols s ON s.file_id = f.id
		GROUP BY f.id`)
	if err != nil {
		return "", err
	}
	defer func() { _ = rows.Close() }()

	counts := make(map[string]int)
	for rows.Next() {
		var fpath string
		var n int
		if err := rows.Scan(&fpath, &n); err != nil {
			return "", err
		}
		ns := namespacePrefixFromPath(fpath)
		counts[ns] += n
	}
	if err := rows.Err(); err != nil {
		return "", err
	}

	type nsEntry struct {
		name    string
		symbols int
	}
	entries := make([]nsEntry, 0, len(counts))
	for name, syms := range counts {
		entries = append(entries, nsEntry{name, syms})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].symbols > entries[j].symbols })

	if len(entries) > 10 {
		entries = entries[:10]
	}

	var b strings.Builder
	for _, e := range entries {
		fmt.Fprintf(&b, "- `%s/` — %d symbols\n", e.name, e.symbols)
	}
	return b.String(), nil
}

func renderHubSymbols(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `SELECT s.qualified, COUNT(e.id) AS in_degree, s.kind
		FROM sense_symbols s
		JOIN sense_edges e ON e.target_id = s.id
		GROUP BY s.id
		ORDER BY in_degree DESC
		LIMIT 8`)
	if err != nil {
		return "", err
	}
	defer func() { _ = rows.Close() }()

	var b strings.Builder
	for rows.Next() {
		var name string
		var callers int
		var kind string
		if err := rows.Scan(&name, &callers, &kind); err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "- `%s` (%s) — %d incoming edges\n", name, kind, callers)
	}
	if b.Len() == 0 {
		return "", nil
	}
	return b.String(), rows.Err()
}

func renderEntryPoints(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `SELECT s.name, f.path
		FROM sense_symbols s
		JOIN sense_files f ON f.id = s.file_id
		WHERE s.name IN ('main', 'Main') AND s.kind = 'function'
		LIMIT 5`)
	if err != nil {
		return "", err
	}
	defer func() { _ = rows.Close() }()

	var b strings.Builder
	for rows.Next() {
		var name, file string
		if err := rows.Scan(&name, &file); err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "- `%s` in `%s`\n", name, file)
	}
	if b.Len() == 0 {
		return "", nil
	}
	return b.String(), rows.Err()
}

func renderConventions(ctx context.Context, db *sql.DB) (string, error) {
	convs, _, err := conventions.Detect(ctx, db, conventions.Options{MinStrength: 0.3})
	if err != nil {
		return "", err
	}

	if len(convs) > 5 {
		convs = convs[:5]
	}

	var b strings.Builder
	for _, c := range convs {
		fmt.Fprintf(&b, "- %s (strength %.0f%%, %d instances)\n",
			c.Description, c.Strength*100, c.Instances)
	}
	if b.Len() == 0 {
		return "", nil
	}
	return b.String(), nil
}

type langEntry struct {
	name    string
	symbols int
}

func queryLanguages(ctx context.Context, db *sql.DB) ([]langEntry, error) {
	rows, err := db.QueryContext(ctx, `SELECT f.language, COUNT(s.id)
		FROM sense_files f
		JOIN sense_symbols s ON s.file_id = f.id
		WHERE f.language != ''
		GROUP BY f.language
		ORDER BY COUNT(s.id) DESC`)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var out []langEntry
	for rows.Next() {
		var lang string
		var n int
		if err := rows.Scan(&lang, &n); err != nil {
			return nil, err
		}
		out = append(out, langEntry{lang, n})
	}
	return out, rows.Err()
}

func queryFrameworks(ctx context.Context, db *sql.DB) []string {
	var val string
	err := db.QueryRowContext(ctx, `SELECT value FROM sense_meta WHERE key = 'frameworks'`).Scan(&val)
	if err != nil || val == "" {
		return nil
	}
	var out []string
	if err := json.Unmarshal([]byte(val), &out); err != nil {
		return nil
	}
	return out
}

func namespacePrefixFromPath(p string) string {
	first, rest, ok := strings.Cut(p, "/")
	if !ok {
		return "."
	}
	if second, _, ok := strings.Cut(rest, "/"); ok {
		return first + "/" + second
	}
	return first
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
