package summary_test

import (
	"bytes"
	"context"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	_ "modernc.org/sqlite"

	"github.com/luuuc/sense/internal/scan"
	"github.com/luuuc/sense/internal/sqlite"
	"github.com/luuuc/sense/internal/summary"
)

func TestGenerateCreatesSummaryFile(t *testing.T) {
	root := t.TempDir()

	writeFile(t, filepath.Join(root, "main.go"), `package main

func main() {}

func helper() int { return 42 }
`)
	writeFile(t, filepath.Join(root, "util.go"), `package main

type Config struct{}

func NewConfig() Config { return Config{} }
`)

	ctx := context.Background()
	if _, err := scan.Run(ctx, scan.Options{
		Root:     root,
		Output:   &bytes.Buffer{},
		Warnings: io.Discard,
	}); err != nil {
		t.Fatalf("scan.Run: %v", err)
	}

	senseDir := filepath.Join(root, ".sense")
	path := filepath.Join(senseDir, "summary.md")

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("summary.md not created: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "# Codebase Summary") {
		t.Error("missing header")
	}
	if !strings.Contains(content, "Fingerprint") {
		t.Error("missing fingerprint section")
	}
	if !strings.Contains(content, "generated by sense") {
		t.Error("missing generated_at header")
	}
}

func TestGenerateRespectsTokenBudget(t *testing.T) {
	root := t.TempDir()

	writeFile(t, filepath.Join(root, "main.go"), `package main

func main() {}
func a() {}
func b() {}
func c() {}
func d() {}
`)

	ctx := context.Background()
	if _, err := scan.Run(ctx, scan.Options{
		Root:     root,
		Output:   &bytes.Buffer{},
		Warnings: io.Discard,
	}); err != nil {
		t.Fatalf("scan.Run: %v", err)
	}

	senseDir := filepath.Join(root, ".sense")
	dbPath := filepath.Join(senseDir, "index.db")

	adapter, err := sqlite.Open(ctx, dbPath)
	if err != nil {
		t.Fatalf("sqlite.Open: %v", err)
	}
	t.Cleanup(func() { _ = adapter.Close() })

	t.Setenv("SENSE_SUMMARY_TOKENS", "200")

	outDir := t.TempDir()
	if err := summary.Generate(ctx, adapter, outDir, root); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "summary.md"))
	if err != nil {
		t.Fatalf("read summary: %v", err)
	}

	charBudget := 200 * 4
	if len(data) > charBudget+200 {
		t.Errorf("summary too large: %d chars, budget was %d tokens (%d chars)",
			len(data), 200, charBudget)
	}
}

func TestGenerateWritesStubWhenEmpty(t *testing.T) {
	ctx := context.Background()
	senseDir := t.TempDir()
	dbPath := filepath.Join(senseDir, "index.db")

	adapter, err := sqlite.Open(ctx, dbPath)
	if err != nil {
		t.Fatalf("sqlite.Open: %v", err)
	}
	t.Cleanup(func() { _ = adapter.Close() })

	outDir := t.TempDir()
	if err := summary.Generate(ctx, adapter, outDir, ""); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "summary.md"))
	if err != nil {
		t.Fatalf("stub summary.md not created: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "No scan data yet") {
		t.Errorf("expected stub message, got: %s", content)
	}
	if !strings.Contains(content, "sense scan") {
		t.Errorf("expected scan instruction, got: %s", content)
	}
}

func TestGenerateTruncatesAndOmitsSections(t *testing.T) {
	root := t.TempDir()

	writeFile(t, filepath.Join(root, "main.go"), `package main

func main() {}
func a() {}
func b() {}
func c() {}
func d() {}
`)
	writeFile(t, filepath.Join(root, "README.md"), "# Test\n\nA project description for testing.\n")

	ctx := context.Background()
	if _, err := scan.Run(ctx, scan.Options{
		Root:     root,
		Output:   &bytes.Buffer{},
		Warnings: io.Discard,
	}); err != nil {
		t.Fatalf("scan.Run: %v", err)
	}

	senseDir := filepath.Join(root, ".sense")
	dbPath := filepath.Join(senseDir, "index.db")

	adapter, err := sqlite.Open(ctx, dbPath)
	if err != nil {
		t.Fatalf("sqlite.Open: %v", err)
	}
	t.Cleanup(func() { _ = adapter.Close() })

	t.Setenv("SENSE_SUMMARY_TOKENS", "30")

	outDir := t.TempDir()
	if err := summary.Generate(ctx, adapter, outDir, root); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "summary.md"))
	if err != nil {
		t.Fatalf("read summary: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "truncated") && !strings.Contains(content, "Omitted") {
		t.Error("expected truncation or omitted marker with tiny token budget")
	}
}

func TestGenerateIncludesProjectSection(t *testing.T) {
	root := t.TempDir()

	writeFile(t, filepath.Join(root, "main.go"), `package main

func main() {}
`)
	writeFile(t, filepath.Join(root, "README.md"), "# TestProj\n\nA project for testing summary generation.\n")

	ctx := context.Background()
	if _, err := scan.Run(ctx, scan.Options{
		Root:     root,
		Output:   &bytes.Buffer{},
		Warnings: io.Discard,
	}); err != nil {
		t.Fatalf("scan.Run: %v", err)
	}

	senseDir := filepath.Join(root, ".sense")
	path := filepath.Join(senseDir, "summary.md")

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("summary.md not created: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "## Project") {
		t.Error("missing Project section")
	}
	if !strings.Contains(content, "A project for testing summary generation.") {
		t.Errorf("expected README description in summary, got: %s", content)
	}
}

func TestTokenBudgetEnvVar(t *testing.T) {
	t.Setenv("SENSE_SUMMARY_TOKENS", "4000")
	if got := summary.TokenBudget(); got != 4000 {
		t.Errorf("TokenBudget() = %d, want 4000", got)
	}
}

func TestTokenBudgetDefault(t *testing.T) {
	t.Setenv("SENSE_SUMMARY_TOKENS", "")
	if got := summary.TokenBudget(); got != summary.DefaultTokenBudget {
		t.Errorf("TokenBudget() = %d, want %d", got, summary.DefaultTokenBudget)
	}
}

func TestGenerateStoresProjectDescriptionInMeta(t *testing.T) {
	root := t.TempDir()

	writeFile(t, filepath.Join(root, "main.go"), `package main

func main() {}
`)
	writeFile(t, filepath.Join(root, "package.json"), `{"name":"test","description":"A test project from package.json"}`)

	ctx := context.Background()
	if _, err := scan.Run(ctx, scan.Options{
		Root:     root,
		Output:   &bytes.Buffer{},
		Warnings: io.Discard,
	}); err != nil {
		t.Fatalf("scan.Run: %v", err)
	}

	senseDir := filepath.Join(root, ".sense")
	dbPath := filepath.Join(senseDir, "index.db")

	adapter, err := sqlite.Open(ctx, dbPath)
	if err != nil {
		t.Fatalf("sqlite.Open: %v", err)
	}
	t.Cleanup(func() { _ = adapter.Close() })

	outDir := t.TempDir()
	if err := summary.Generate(ctx, adapter, outDir, root); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	var desc string
	if err := adapter.DB().QueryRowContext(ctx, "SELECT value FROM sense_meta WHERE key = 'project_description'").Scan(&desc); err != nil {
		t.Fatalf("read meta: %v", err)
	}
	if desc != "A test project from package.json" {
		t.Errorf("project_description = %q, want %q", desc, "A test project from package.json")
	}
}

func TestGenerateIncludesQuickOrientation(t *testing.T) {
	root := t.TempDir()

	// main calls A, B, C — so main is an entry point (zero callers, ≥3 callees).
	// A is called by main and by helper — A is a hub symbol (2 callers).
	writeFile(t, filepath.Join(root, "main.go"), `package main

func main() { A(); B(); C() }
func A() {}
func B() {}
func C() {}
func helper() { A() }
`)

	ctx := context.Background()
	if _, err := scan.Run(ctx, scan.Options{
		Root:     root,
		Output:   &bytes.Buffer{},
		Warnings: io.Discard,
	}); err != nil {
		t.Fatalf("scan.Run: %v", err)
	}

	senseDir := filepath.Join(root, ".sense")
	data, err := os.ReadFile(filepath.Join(senseDir, "summary.md"))
	if err != nil {
		t.Fatalf("summary.md not created: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Quick Orientation") {
		t.Error("missing Quick Orientation section")
	}
	// main has zero callers and calls A, B, C (≥3 callees) — should be an entry point.
	if !strings.Contains(content, "Entry points") {
		t.Error("Quick Orientation should contain entry points")
	}
	if !strings.Contains(content, "main.main") {
		t.Error("Quick Orientation entry points should include main.main (qualified)")
	}
	// A has 2 callers (main + helper) — should appear in hub symbols.
	if !strings.Contains(content, "Hub symbols") {
		t.Error("Quick Orientation should contain hub symbols")
	}
}

func TestGenerateQuickOrientationTestStructure(t *testing.T) {
	root := t.TempDir()

	writeFile(t, filepath.Join(root, "main.go"), `package main

func main() { A(); B(); C() }
func A() {}
func B() {}
func C() {}
`)
	writeFile(t, filepath.Join(root, "main_test.go"), `package main

import "testing"

func TestA(t *testing.T) { A() }
func TestB(t *testing.T) { B() }
`)

	ctx := context.Background()
	if _, err := scan.Run(ctx, scan.Options{
		Root:     root,
		Output:   &bytes.Buffer{},
		Warnings: io.Discard,
	}); err != nil {
		t.Fatalf("scan.Run: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(root, ".sense", "summary.md"))
	if err != nil {
		t.Fatalf("summary.md not created: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Test structure") {
		t.Error("Quick Orientation should contain test structure when test files exist")
	}
	if !strings.Contains(content, "test file") {
		t.Error("Test structure should mention test files")
	}
	if strings.Contains(content, "Key patterns") {
		t.Error("Quick Orientation should not contain key patterns (removed)")
	}
}

func TestGenerateQuickOrientationHubOrder(t *testing.T) {
	root := t.TempDir()

	// Create a fixture where hub ordering is clear:
	// Hub called by 3 callers, Other called by 1.
	writeFile(t, filepath.Join(root, "main.go"), `package main

func Hub() {}
func Other() {}
func C1() { Hub() }
func C2() { Hub() }
func C3() { Hub(); Other() }
`)

	ctx := context.Background()
	if _, err := scan.Run(ctx, scan.Options{
		Root:     root,
		Output:   &bytes.Buffer{},
		Warnings: io.Discard,
	}); err != nil {
		t.Fatalf("scan.Run: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(root, ".sense", "summary.md"))
	if err != nil {
		t.Fatalf("summary.md not created: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Hub symbols") {
		t.Fatal("missing Hub symbols line")
	}
	// Hub should appear before Other (more callers).
	hubIdx := strings.Index(content, "`main.Hub`")
	otherIdx := strings.Index(content, "`main.Other`")
	if hubIdx < 0 {
		t.Error("Hub should appear in hub symbols")
	}
	if otherIdx >= 0 && hubIdx > otherIdx {
		t.Error("Hub should appear before Other (more callers)")
	}
}

// scanAdapter scans a root and returns an open adapter over its index.
func scanAdapter(t *testing.T, root string) *sqlite.Adapter {
	t.Helper()
	ctx := context.Background()
	if _, err := scan.Run(ctx, scan.Options{
		Root:     root,
		Output:   &bytes.Buffer{},
		Warnings: io.Discard,
	}); err != nil {
		t.Fatalf("scan.Run: %v", err)
	}
	adapter, err := sqlite.Open(ctx, filepath.Join(root, ".sense", "index.db"))
	if err != nil {
		t.Fatalf("sqlite.Open: %v", err)
	}
	t.Cleanup(func() { _ = adapter.Close() })
	return adapter
}

// TestGenerateTruncatesMidSection drives the in-block truncation path (remaining > 80).
func TestGenerateTruncatesMidSection(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "main.go"), `package main

func main() {}
`)
	// A long README so the Project section is large enough to overflow but
	// leave a sizeable remaining budget after the Fingerprint section.
	writeFile(t, filepath.Join(root, "README.md"),
		"# Proj\n\n"+strings.Repeat("Useful detail about this project. ", 10)+"\n")

	adapter := scanAdapter(t, root)

	t.Setenv("SENSE_SUMMARY_TOKENS", "70")

	outDir := t.TempDir()
	if err := summary.Generate(context.Background(), adapter, outDir, root); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(outDir, "summary.md"))
	if err != nil {
		t.Fatalf("read summary: %v", err)
	}
	if !strings.Contains(string(data), "truncated") {
		t.Errorf("expected mid-section truncation marker, got:\n%s", data)
	}
}

// TestGenerateFileCountQueryError surfaces the error path when sense_files is gone.
func TestGenerateFileCountQueryError(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "main.go"), "package main\n\nfunc main() {}\n")
	adapter := scanAdapter(t, root)

	if _, err := adapter.DB().ExecContext(context.Background(), "DROP TABLE sense_files"); err != nil {
		t.Fatal(err)
	}
	if err := summary.Generate(context.Background(), adapter, t.TempDir(), ""); err == nil {
		t.Error("expected error when sense_files is missing")
	}
}

// TestGenerateMkdirError surfaces the error path when the sense dir cannot be created.
func TestGenerateMkdirError(t *testing.T) {
	ctx := context.Background()
	senseDir := t.TempDir()
	adapter, err := sqlite.Open(ctx, filepath.Join(senseDir, "index.db"))
	if err != nil {
		t.Fatalf("sqlite.Open: %v", err)
	}
	t.Cleanup(func() { _ = adapter.Close() })

	// fileCount == 0 path: target a sense dir whose parent is a regular file.
	blocker := filepath.Join(t.TempDir(), "blocker")
	if err := os.WriteFile(blocker, []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	out := filepath.Join(blocker, "sub")
	if err := summary.Generate(ctx, adapter, out, ""); err == nil {
		t.Error("expected MkdirAll error when parent is a file")
	}
}

// TestGenerateWriteMetaError surfaces the error path when project_description cannot be persisted.
func TestGenerateWriteMetaError(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "main.go"), "package main\n\nfunc main() {}\n")
	writeFile(t, filepath.Join(root, "README.md"), "# Proj\n\nA real description here.\n")
	adapter := scanAdapter(t, root)

	// Drop sense_meta so WriteMeta (project_description) fails while files exist.
	if _, err := adapter.DB().ExecContext(context.Background(), "DROP TABLE sense_meta"); err != nil {
		t.Fatal(err)
	}
	if err := summary.Generate(context.Background(), adapter, t.TempDir(), root); err == nil {
		t.Error("expected WriteMeta error when sense_meta is missing")
	}
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
}
