#!/usr/bin/env bash
set -euo pipefail

# Freeze held-out transcripts. One-time setup.
#
# For each (tool, held-out scenario) pair:
#   1. Ensure the per-tool repo is cloned and indexed (sense scan, etc.).
#   2. Run a single Claude session against the scenario's prompt.
#   3. Save transcript.json + run_meta.json under
#      bench2/scenarios/held-out/transcripts/<tool>/<repo>/.
#
# The transcripts are frozen — committed and never re-generated by the loop.
# The loop only re-scores them per iteration.

BENCH2_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$BENCH2_DIR/.." && pwd)"
BENCH2_PROJECT_ROOT="$PROJECT_ROOT"
# shellcheck disable=SC1091
source "$BENCH2_DIR/lib/load-env.sh"
TOOLS_DIR="$BENCH2_DIR/tools"
HELDOUT_DIR="$BENCH2_DIR/scenarios/held-out"
TRANSCRIPTS_DIR="$HELDOUT_DIR/transcripts"
LIB_DIR="$BENCH2_DIR/lib"
SENSE_BENCH_ROOT="${SENSE_BENCH_ROOT:-$(cd "$PROJECT_ROOT/.." && pwd)/sense-benchmark}"
REF_DIR="$SENSE_BENCH_ROOT/_reference"
PINNED_COMMITS="$PROJECT_ROOT/bench/PINNED_COMMITS.json"

READY_POLL_INTERVAL=5
READY_POLL_MAX=720
SETUP_TIMEOUT=600
MAX_BUDGET_USD="2.00"
SESSION_TIMEOUT=1800   # 30 min — generous for held-out one-shots

FILTER_TOOLS="sense,baseline"
FILTER_SCENARIOS=""
DRY_RUN=false
FORCE=false
MODEL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tool) FILTER_TOOLS="$2"; shift 2 ;;
    --scenario) FILTER_SCENARIOS="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --force) FORCE=true; shift ;;
    --budget) MAX_BUDGET_USD="$2"; shift 2 ;;
    --timeout) SESSION_TIMEOUT="$2"; shift 2 ;;
    --model) MODEL="$2"; shift 2 ;;
    -h|--help)
      cat <<EOF
Usage: freeze-heldout.sh [options]

Freeze held-out transcripts. One-time setup; transcripts are committed
and never re-generated by the improvement loop.

Options:
  --tool        Comma-separated tool filter (default: sense,baseline)
  --scenario    Comma-separated scenario slug filter (e.g. flask-blueprints)
  --dry-run     Show what would run; do not invoke Claude
  --force       Re-freeze even if transcript.json already exists
  --budget USD  Max USD per Claude session (default: $MAX_BUDGET_USD)
  --timeout S   Per-session timeout in seconds (default: $SESSION_TIMEOUT)
  --model M     Claude model (e.g. sonnet, opus)
EOF
      exit 0
      ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

matches_filter() {
  local value="$1" filter="$2"
  [[ -z "$filter" ]] && return 0
  echo "$filter" | tr ',' '\n' | grep -qx "$value"
}

timestamp() { date +%Y-%m-%dT%H:%M:%S; }
log() { echo "[$(timestamp)] $*" >&2; }

tool_repo_path() {
  local tool="$1" repo="$2"
  echo "$SENSE_BENCH_ROOT/$tool/$repo"
}

ensure_tool_repo() {
  local tool="$1" repo="$2"
  local dest
  dest=$(tool_repo_path "$tool" "$repo")
  if [[ -d "$dest/.git" ]]; then
    return 0
  fi
  local ref="$REF_DIR/$repo"
  if [[ ! -d "$ref/.git" ]]; then
    log "  ERROR: reference repo missing: $ref"
    log "  For non-sense repos: bash bench/bootstrap-repos.sh --repo $repo"
    log "  For sense: see card 2 of pitch 20-07 (held_out: true in PINNED_COMMITS.json)"
    return 1
  fi
  log "  cloning $repo for $tool (--reference from _reference/)..."
  mkdir -p "$(dirname "$dest")"
  git clone --quiet --reference "$ref" "$ref" "$dest"
  local pinned
  pinned=$(python3 -c "
import sys,json
v=json.load(open(sys.argv[1])).get(sys.argv[2])
if isinstance(v, dict): v=v.get('commit')
print(v if v else '')
" "$PINNED_COMMITS" "$repo")
  if [[ -n "$pinned" ]]; then
    (cd "$dest" && git -c advice.detachedHead=false checkout "$pinned" --quiet)
  fi
}

TIMEOUT_CMD=""
if command -v timeout &>/dev/null; then TIMEOUT_CMD="timeout"
elif command -v gtimeout &>/dev/null; then TIMEOUT_CMD="gtimeout"
fi

run_with_timeout() {
  local secs="$1"; shift
  if [[ -n "$TIMEOUT_CMD" ]]; then
    "$TIMEOUT_CMD" "$secs" "$@"
  else
    "$@" &
    local pid=$!
    ( sleep "$secs" && kill "$pid" 2>/dev/null ) &
    local watchdog=$!
    wait "$pid" 2>/dev/null
    local rc=$?
    kill "$watchdog" 2>/dev/null
    wait "$watchdog" 2>/dev/null
    return $rc
  fi
}

# --- Discover held-out scenarios ---

if [[ ! -d "$HELDOUT_DIR" ]]; then
  echo "Held-out scenarios dir missing: $HELDOUT_DIR" >&2
  exit 2
fi

scenarios=()
scenario_files=()
scenario_repos=()
for scenariofile in "$HELDOUT_DIR"/*.yaml; do
  [[ -f "$scenariofile" ]] || continue
  name="$(basename "$scenariofile" .yaml)"
  # Skip rubric files
  [[ "$name" == *.rubric ]] && continue
  repo=$(python3 -c "
import sys,yaml
d=yaml.safe_load(open(sys.argv[1]))
print(d.get('repo', ''))
" "$scenariofile" 2>/dev/null || echo "")
  if [[ -z "$repo" ]]; then continue; fi
  matches_filter "$name" "$FILTER_SCENARIOS" || continue
  scenarios+=("$name")
  scenario_files+=("$scenariofile")
  scenario_repos+=("$repo")
done

if [[ ${#scenarios[@]} -eq 0 ]]; then
  echo "No held-out scenarios matched" >&2
  exit 1
fi

IFS=',' read -r -a tools <<< "$FILTER_TOOLS"

# --- Dry-run / inventory ---

total=$(( ${#tools[@]} * ${#scenarios[@]} ))
log "Held-out freeze: ${#tools[@]} tools x ${#scenarios[@]} scenarios = $total transcripts"
log "Tools:     ${tools[*]}"
log "Scenarios: ${scenarios[*]}"

if $DRY_RUN; then
  echo ""
  echo "=== DRY RUN ==="
  echo ""
  n=0
  for tool in "${tools[@]}"; do
    for i in "${!scenarios[@]}"; do
      n=$((n + 1))
      sc="${scenarios[$i]}"
      repo="${scenario_repos[$i]}"
      out="$TRANSCRIPTS_DIR/$tool/$repo/transcript.json"
      exists="(new)"
      if [[ -f "$out" ]] && ! $FORCE; then exists="(exists, skip)"; fi
      echo "  [$n/$total] tool=$tool scenario=$sc repo=$repo $exists"
    done
  done
  echo ""
  echo "Estimated cost: up to \$$(echo "$total * $MAX_BUDGET_USD" | bc) (ceiling, not actual)"
  exit 0
fi

# --- Suppress Sense hook injection (same as run.sh) ---
export SENSE_BENCH=1

# --- Neutralize user-level config (same as run.sh) ---
USER_SETTINGS="$HOME/.claude/settings.json"
USER_MCP_CONFIG="$HOME/.claude/.mcp.json"
USER_SETTINGS_BACKUP=""
USER_MCP_BACKUP=""

restore_user_settings() {
  if [[ -n "${USER_SETTINGS_BACKUP:-}" && -f "$USER_SETTINGS_BACKUP" ]]; then
    cp "$USER_SETTINGS_BACKUP" "$USER_SETTINGS"
    rm -f "$USER_SETTINGS_BACKUP"
    log "Restored ~/.claude/settings.json"
  fi
  if [[ -n "${USER_MCP_BACKUP:-}" && -f "$USER_MCP_BACKUP" ]]; then
    cp "$USER_MCP_BACKUP" "$USER_MCP_CONFIG"
    rm -f "$USER_MCP_BACKUP"
    log "Restored ~/.claude/.mcp.json"
  fi
}

strip_user_hooks() {
  python3 -c "
import json
with open('$USER_SETTINGS') as f: d = json.load(f)
d.pop('hooks', None)
with open('$USER_SETTINGS', 'w') as f:
    json.dump(d, f, indent=2); f.write('\n')
"
}

strip_user_mcp() {
  python3 -c "
import json
with open('$USER_MCP_CONFIG') as f: d = json.load(f)
d['mcpServers'] = {}
with open('$USER_MCP_CONFIG', 'w') as f:
    json.dump(d, f, indent=2); f.write('\n')
"
}

trap restore_user_settings EXIT

if [[ -f "$USER_SETTINGS" ]] && grep -q 'cbm-' "$USER_SETTINGS" 2>/dev/null; then
  USER_SETTINGS_BACKUP=$(mktemp)
  cp "$USER_SETTINGS" "$USER_SETTINGS_BACKUP"
  strip_user_hooks
  log "Stripped hooks from ~/.claude/settings.json"
fi

if [[ -f "$USER_MCP_CONFIG" ]] && grep -q 'mcpServers' "$USER_MCP_CONFIG" 2>/dev/null; then
  USER_MCP_BACKUP=$(mktemp)
  cp "$USER_MCP_CONFIG" "$USER_MCP_BACKUP"
  strip_user_mcp
  log "Stripped MCP servers from ~/.claude/.mcp.json"
fi

# --- Main freeze loop ---

n=0
produced=0
skipped=0
failed=0

for tool in "${tools[@]}"; do
  for i in "${!scenarios[@]}"; do
    n=$((n + 1))
    sc="${scenarios[$i]}"
    sf="${scenario_files[$i]}"
    repo="${scenario_repos[$i]}"
    out_dir="$TRANSCRIPTS_DIR/$tool/$repo"
    out_transcript="$out_dir/transcript.json"

    log "[$n/$total] tool=$tool scenario=$sc repo=$repo"

    if [[ -f "$out_transcript" ]] && ! $FORCE; then
      log "  SKIP: already frozen at $out_transcript (use --force to overwrite)"
      skipped=$((skipped + 1))
      continue
    fi

    if ! ensure_tool_repo "$tool" "$repo"; then
      log "  FAIL: reference repo not available"
      failed=$((failed + 1))
      continue
    fi

    rp=$(tool_repo_path "$tool" "$repo")
    workspace="$SENSE_BENCH_ROOT/$tool/$repo/.workspace"
    mkdir -p "$workspace" "$out_dir"

    # Setup if not already indexed
    "$TOOLS_DIR/$tool.sh" --check-ready "$rp" "$workspace" >/dev/null 2>/dev/null && ready_rc=0 || ready_rc=$?
    if [[ $ready_rc -eq 0 ]]; then
      log "  $tool x $repo already indexed — writing config only"
      "$TOOLS_DIR/$tool.sh" --write-config "$rp" "$workspace"
    else
      log "  setting up $tool for $repo..."
      if ! run_with_timeout "$SETUP_TIMEOUT" "$TOOLS_DIR/$tool.sh" "$rp" "$workspace"; then
        log "  FAIL: setup failed"
        failed=$((failed + 1))
        continue
      fi
      ready=false
      for poll in $(seq 1 $READY_POLL_MAX); do
        "$TOOLS_DIR/$tool.sh" --check-ready "$rp" "$workspace" >/dev/null 2>/dev/null && rc=0 || rc=$?
        if [[ $rc -eq 0 ]]; then ready=true; break; fi
        sleep $READY_POLL_INTERVAL
      done
      if [[ "$ready" != "true" ]]; then
        log "  FAIL: index never became ready"
        failed=$((failed + 1))
        continue
      fi
    fi

    prompt=$(python3 "$LIB_DIR/scenario.py" "$sf" --prompt)
    claude_md=$(cat "$workspace/CLAUDE.md" 2>/dev/null || echo "")

    claude_args=(
      -p "$prompt"
      --verbose
      --append-system-prompt "$claude_md"
      --output-format stream-json
      --permission-mode bypassPermissions
      --disallowed-tools "Agent"
      --max-budget-usd "$MAX_BUDGET_USD"
    )
    [[ -n "$MODEL" ]] && claude_args+=(--model "$MODEL")
    [[ -f "$workspace/.mcp.json" ]] && claude_args+=(--mcp-config "$workspace/.mcp.json")

    log "  running Claude session (budget=\$$MAX_BUDGET_USD timeout=${SESSION_TIMEOUT}s)..."
    start_time=$(date +%s)
    (cd "$rp" && run_with_timeout "$SESSION_TIMEOUT" claude "${claude_args[@]}" > "$out_transcript" 2>"$out_dir/claude.log") && rc=0 || rc=$?
    end_time=$(date +%s)
    wall=$((end_time - start_time))

    tool_version=$(grep -m1 '^TOOL_VERSION=' "$TOOLS_DIR/$tool.sh" 2>/dev/null | cut -d'"' -f2 || echo "")
    repo_commit=$(cd "$rp" && git rev-parse --short HEAD 2>/dev/null || echo "")

    if [[ $rc -eq 0 ]]; then
      log "  done in ${wall}s"
      python3 -c "
import json, sys
meta = {
  'tool': sys.argv[1], 'repo': sys.argv[2], 'scenario': sys.argv[3],
  'wall_time_seconds': int(sys.argv[4]), 'max_budget_usd': float(sys.argv[5]),
  'timestamp': sys.argv[6], 'tool_version': sys.argv[7] or None,
  'repo_commit': sys.argv[8] or None, 'model': sys.argv[9] or None,
  'held_out': True,
}
json.dump(meta, sys.stdout, indent=2); print()
" "$tool" "$repo" "$sc" "$wall" "$MAX_BUDGET_USD" "$(timestamp)" "$tool_version" "$repo_commit" "$MODEL" > "$out_dir/run_meta.json"
      produced=$((produced + 1))
    else
      log "  FAIL: Claude session failed after ${wall}s (rc=$rc)"
      python3 -c "
import json, sys
meta = {
  'tool': sys.argv[1], 'repo': sys.argv[2], 'scenario': sys.argv[3],
  'wall_time_seconds': int(sys.argv[4]), 'max_budget_usd': float(sys.argv[5]),
  'timestamp': sys.argv[6], 'error': 'claude_session_failed',
  'claude_exit_code': int(sys.argv[7]), 'model': sys.argv[8] or None,
  'held_out': True,
}
json.dump(meta, sys.stdout, indent=2); print()
" "$tool" "$repo" "$sc" "$wall" "$MAX_BUDGET_USD" "$(timestamp)" "$rc" "$MODEL" > "$out_dir/run_meta.json"
      failed=$((failed + 1))
    fi
  done
done

log ""
log "=== Held-out freeze complete ==="
log "  Total: $total | Produced: $produced | Skipped: $skipped | Failed: $failed"
log "  Transcripts: $TRANSCRIPTS_DIR/"
