package scan

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/luuuc/sense/internal/sqlite"
)

func TestIsGeneratedSource(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "exact protoc marker",
			src:  "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n",
			want: true,
		},
		{
			name: "marker after license block and build tag",
			src: "/*\nCopyright 2020 The Authors.\n\nLicensed under the Apache License.\n*/\n\n" +
				"//go:build !purego\n\n// Code generated by stringer. DO NOT EDIT.\n\npackage x\n",
			want: true,
		},
		{
			name: "near-miss marker missing DO NOT EDIT stays indexed",
			src:  "// Code generated by protoc-gen-go.\n\npackage pb\n",
			want: false,
		},
		{
			name: "near-miss wrong case stays indexed",
			src:  "// code generated by mockgen. DO NOT EDIT.\n\npackage mocks\n",
			want: false,
		},
		{
			name: "marker with trailing text stays indexed",
			src:  "// Code generated by wire. DO NOT EDIT. (see docs)\n\npackage di\n",
			want: false,
		},
		{
			name: "marker after package clause is not a header",
			src:  "package pb\n\n// Code generated by protoc-gen-go. DO NOT EDIT.\n",
			want: false,
		},
		{
			name: "BOM and CRLF endings",
			src:  "\xEF\xBB\xBF// Code generated by protoc-gen-go. DO NOT EDIT.\r\n\r\npackage pb\r\n",
			want: true,
		},
		{
			name: "indented marker matches like go/ast comment text",
			src:  "  // Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n",
			want: true,
		},
		{
			name: "marker inside a block comment does not match",
			src:  "/*\n// Code generated by protoc-gen-go. DO NOT EDIT.\n*/\n\npackage pb\n",
			want: false,
		},
		{
			name: "code after block close on same line stops the scan",
			src:  "/* header */ package pb\n// Code generated by protoc-gen-go. DO NOT EDIT.\n",
			want: false,
		},
		{
			name: "single-line block comment then marker",
			src:  "/* Copyright 2020 */\n// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n",
			want: true,
		},
		{
			// Two block comments on one line: the scan conservatively treats
			// the remainder after the first close as code and stops — fails
			// toward indexing, as documented on classifyHeaderLine.
			name: "double block comment line stops the scan conservatively",
			src:  "/* a */ /* b */\n// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n",
			want: false,
		},
		{
			name: "unclosed block comment never matches",
			src:  "/*\nCopyright\n",
			want: false,
		},
		{
			name: "empty file",
			src:  "",
			want: false,
		},
		{
			name: "blank lines only",
			src:  "\n\n\n",
			want: false,
		},
		{
			name: "plain source file exits at first code line",
			src:  "package a\n\nfunc Hello() {}\n",
			want: false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := isGeneratedSource([]byte(tc.src)); got != tc.want {
				t.Errorf("isGeneratedSource = %v, want %v", got, tc.want)
			}
		})
	}
}

// faultDeleteStore is the seam substitution for processFile's eviction
// failure branch: it embeds the real adapter and fails exactly one named
// method, DeleteFile — same one-method shape as rollback's faultWriteStore.
type faultDeleteStore struct {
	*sqlite.Adapter
}

var errInjectedDelete = errors.New("injected DeleteFile failure")

func (f *faultDeleteStore) DeleteFile(context.Context, string) error {
	return errInjectedDelete
}

func TestProcessFileWarnsWhenEvictionDeleteFails(t *testing.T) {
	// A generated file whose eviction delete fails must warn and NOT count
	// as removed — the next full scan's stale pass self-heals.
	dir := t.TempDir()
	path := filepath.Join(dir, "gen.pb.go")
	src := "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n"
	if err := os.WriteFile(path, []byte(src), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	adapter := openIndex(t, dir)
	defer func() { _ = adapter.Close() }()

	h := &harness{
		ctx:       context.Background(),
		idx:       &faultDeleteStore{adapter},
		seenPaths: map[string]bool{},
		collector: newWarningCollector(),
		progress:  &progress{},
	}
	h.processFile(path, "gen.pb.go")

	if h.removed != 0 {
		t.Errorf("removed = %d, want 0 (failed delete must not count)", h.removed)
	}
	if h.seenPaths["gen.pb.go"] {
		t.Error("gen.pb.go left in seenPaths; generated files leave the visit set")
	}
	if got := h.collector.count(); got == 0 {
		t.Error("expected a write-failed warning for the injected delete error")
	}
	if out := h.collector.format(); !strings.Contains(out, errInjectedDelete.Error()) {
		t.Errorf("warning must carry the injected failure; got %q", out)
	}
}

func TestGeneratedCheckRunsBeforeHashSkip(t *testing.T) {
	// The upgrade path depends on this ordering: a pre-hygiene index holds
	// generated rows whose content hash will NOT change on rescan, so the
	// hash-skip would keep them as cached rows forever. parseFileCore must
	// return the Generated sentinel even when skip reports the hash as
	// unchanged.
	dir := t.TempDir()
	path := filepath.Join(dir, "gen.pb.go")
	src := "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n"
	if err := os.WriteFile(path, []byte(src), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	po := parseOpts{
		ctx:   context.Background(),
		warnf: func(warningKind, string, ...any) {},
	}
	fr := parseFileCore(po, path, "gen.pb.go", func(string) bool { return true })
	if fr == nil {
		t.Fatal("parseFileCore = nil; the hash-skip ran before the generated check")
	}
	if !fr.Generated {
		t.Errorf("Generated = false, want true")
	}
}
