package scan_test

import (
	"bytes"
	"context"
	"io"
	"path/filepath"
	"testing"

	"github.com/luuuc/sense/internal/ignore"
	"github.com/luuuc/sense/internal/scan"
	"github.com/luuuc/sense/internal/sqlite"
)

const generatedHeader = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\n"

// indexedPaths returns the file paths currently tracked by the index at root.
func indexedPaths(t *testing.T, root string) map[string]bool {
	t.Helper()
	ctx := context.Background()
	adapter, err := sqlite.Open(ctx, filepath.Join(root, ".sense", "index.db"))
	if err != nil {
		t.Fatalf("open index: %v", err)
	}
	defer func() { _ = adapter.Close() }()
	rows, err := adapter.DB().QueryContext(ctx, `SELECT path FROM sense_files`)
	if err != nil {
		t.Fatalf("query files: %v", err)
	}
	defer func() { _ = rows.Close() }()
	paths := map[string]bool{}
	for rows.Next() {
		var p string
		if err := rows.Scan(&p); err != nil {
			t.Fatalf("scan row: %v", err)
		}
		paths[p] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}
	return paths
}

func TestScanSkipsGeneratedFiles(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "a.go"), "package a\n\nfunc Hello() {}\n")
	writeFile(t, filepath.Join(root, "gen.pb.go"), generatedHeader+"package a\n\nfunc Generated() {}\n")

	res, err := scan.Run(context.Background(), quietOpts(root))
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if res.Files != 2 {
		t.Errorf("Files = %d, want 2 (generated file is still visited)", res.Files)
	}
	if res.Indexed != 1 {
		t.Errorf("Indexed = %d, want 1 (generated file must not be indexed)", res.Indexed)
	}

	paths := indexedPaths(t, root)
	if paths["gen.pb.go"] {
		t.Error("gen.pb.go was indexed; generated files must be skipped")
	}
	if !paths["a.go"] {
		t.Error("a.go missing from index")
	}
}

func TestScanIndexesNearMissGeneratedHeader(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "gen.go"), "// Code generated by hand.\npackage a\n\nfunc Kept() {}\n")

	res, err := scan.Run(context.Background(), quietOpts(root))
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if res.Indexed != 1 {
		t.Errorf("Indexed = %d, want 1 (near-miss header must stay indexed)", res.Indexed)
	}
	if !indexedPaths(t, root)["gen.go"] {
		t.Error("gen.go with a near-miss header must stay indexed")
	}
}

func TestScanEvictsPreviouslyIndexedGeneratedFile(t *testing.T) {
	root := t.TempDir()
	ctx := context.Background()
	writeFile(t, filepath.Join(root, "gen.go"), "package a\n\nfunc Soon() {}\n")

	if _, err := scan.Run(ctx, quietOpts(root)); err != nil {
		t.Fatalf("first Run: %v", err)
	}
	if !indexedPaths(t, root)["gen.go"] {
		t.Fatal("gen.go should be indexed before it grows the marker")
	}

	// The file is regenerated with the marker; the next scan must evict it
	// even though nothing else changed.
	writeFile(t, filepath.Join(root, "gen.go"), generatedHeader+"package a\n\nfunc Soon() {}\n")
	res, err := scan.Run(ctx, quietOpts(root))
	if err != nil {
		t.Fatalf("second Run: %v", err)
	}
	if res.Removed != 1 {
		t.Errorf("Removed = %d, want 1 (stale-removal evicts the generated file)", res.Removed)
	}
	if indexedPaths(t, root)["gen.go"] {
		t.Error("gen.go still indexed after gaining the generated marker")
	}
}

func TestScanSkipsTestdataDir(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "main.go"), "package main\n\nfunc main() {}\n")
	writeFile(t, filepath.Join(root, "testdata", "fixture.go"), "package fixture\n\nfunc Fixture() {}\n")
	writeFile(t, filepath.Join(root, "pkg", "testdata", "deep.go"), "package deep\n\nfunc Deep() {}\n")

	res, err := scan.Run(context.Background(), quietOpts(root))
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if res.Files != 1 {
		t.Errorf("Files = %d, want 1 (testdata/ is skipped at walk time at any depth)", res.Files)
	}
	paths := indexedPaths(t, root)
	if paths["testdata/fixture.go"] || paths["pkg/testdata/deep.go"] {
		t.Error("testdata/ contents must not be indexed")
	}
}

func TestSenseignoreReincludesTestdata(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "main.go"), "package main\n\nfunc main() {}\n")
	writeFile(t, filepath.Join(root, "testdata", "golden.go"), "package golden\n\nfunc Golden() {}\n")
	writeFile(t, filepath.Join(root, ".senseignore"), "!testdata/\n")

	if _, err := scan.Run(context.Background(), quietOpts(root)); err != nil {
		t.Fatalf("Run: %v", err)
	}
	if !indexedPaths(t, root)["testdata/golden.go"] {
		t.Error("!testdata/ in .senseignore must re-include load-bearing fixtures")
	}
}

func TestIncrementalEvictsGeneratedFile(t *testing.T) {
	root := t.TempDir()
	ctx := context.Background()
	writeFile(t, filepath.Join(root, "gen.go"), "package a\n\nfunc Soon() {}\n")

	if _, err := scan.Run(ctx, quietOpts(root)); err != nil {
		t.Fatalf("initial scan: %v", err)
	}

	writeFile(t, filepath.Join(root, "gen.go"), generatedHeader+"package a\n\nfunc Soon() {}\n")

	adapter, err := sqlite.Open(ctx, filepath.Join(root, ".sense", "index.db"))
	if err != nil {
		t.Fatalf("open adapter: %v", err)
	}
	defer func() { _ = adapter.Close() }()
	matcher, err := ignore.Build(root, nil)
	if err != nil {
		t.Fatalf("build matcher: %v", err)
	}

	res, err := scan.RunIncremental(ctx, scan.IncrementalOptions{
		Root:          root,
		Idx:           adapter,
		Matcher:       matcher,
		MaxFileSizeKB: 512,
		Output:        io.Discard,
		Warnings:      &bytes.Buffer{},
		Changed:       []string{"gen.go"},
	})
	if err != nil {
		t.Fatalf("RunIncremental: %v", err)
	}
	if res.Removed != 1 {
		t.Errorf("Removed = %d, want 1 (eviction must be visible so the summary regenerates)", res.Removed)
	}

	var count int
	if err := adapter.DB().QueryRowContext(ctx,
		`SELECT COUNT(*) FROM sense_files WHERE path = 'gen.go'`).Scan(&count); err != nil {
		t.Fatalf("query: %v", err)
	}
	if count != 0 {
		t.Error("gen.go still indexed after incremental scan saw the generated marker")
	}
}
