package scan

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
	"unicode/utf8"
)

// snippetMaxBytes caps the single-line snippet we store per symbol.
// Large minified lines (bundled JS, generated protos) would otherwise
// balloon the index with source text that nobody reads.
const snippetMaxBytes = 200

// docstringMaxBytes caps the stored docstring at 2 KB. Real doc comments
// are almost always <300 chars; the cap is a sanity bound so a pathological
// 50 KB block comment can't bloat the symbols table.
const docstringMaxBytes = 2048

// docstringTruncMarker is appended (in place of the cut tail) when a
// docstring exceeds docstringMaxBytes. The single rune is enough to
// signal truncation to a reader without inflating storage.
const docstringTruncMarker = "…"

// int64Ptr returns a pointer to v, or nil if v is 0 (sentinel for file-level edges).
func int64Ptr(v int64) *int64 {
	if v == 0 {
		return nil
	}
	return &v
}

func printPhaseBreakdown(out io.Writer, total time.Duration, p PhaseTiming) {
	pct := func(d time.Duration) int {
		if total == 0 {
			return 0
		}
		return int(100 * d / total)
	}
	_, _ = fmt.Fprintf(out, "phases: walk %s (%d%%), stale %s (%d%%), edges %s (%d%%), interfaces %s (%d%%), tests %s (%d%%), naming %s (%d%%), temporal %s (%d%%)",
		p.Walk, pct(p.Walk),
		p.RemoveStale, pct(p.RemoveStale),
		p.ResolveEdges, pct(p.ResolveEdges),
		p.SatisfyInterfaces, pct(p.SatisfyInterfaces),
		p.AssociateTests, pct(p.AssociateTests),
		p.NamingConventions, pct(p.NamingConventions),
		p.Temporal, pct(p.Temporal))
	if p.Embed > 0 {
		_, _ = fmt.Fprintf(out, ", embed %s (%d%%)", p.Embed, pct(p.Embed))
	}
	_, _ = fmt.Fprintln(out)
}

func addSenseToGitignore(root string) bool {
	gi := filepath.Join(root, ".gitignore")
	data, err := os.ReadFile(gi)
	if err != nil {
		return false
	}

	s := bufio.NewScanner(strings.NewReader(string(data)))
	for s.Scan() {
		line := strings.TrimSpace(s.Text())
		if line == ".sense" || line == ".sense/" {
			return false
		}
	}
	if s.Err() != nil {
		return false
	}

	prefix := "\n"
	if len(data) > 0 && data[len(data)-1] == '\n' {
		prefix = ""
	}

	af, err := os.OpenFile(gi, os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return false
	}
	_, err = fmt.Fprintf(af, "%s# Sense index (auto-generated by sense scan)\n.sense/\n", prefix)
	closeErr := af.Close()
	return err == nil && closeErr == nil
}

// hashSource returns the first 16 hex chars of SHA-256 of the source.
// Truncation is fine for our purposes (change detection, not
// cryptographic identity); 8 bytes of hash are enough for billions of
// files before a meaningful collision.
func hashSource(source []byte) string {
	sum := sha256.Sum256(source)
	return hex.EncodeToString(sum[:8])
}

// capDocstring enforces the 2 KB storage cap on a per-symbol docstring.
// Truncation is byte-bounded but rune-safe: cuts at the last whole rune
// boundary before docstringMaxBytes and appends docstringTruncMarker.
// Returns the input unchanged when within the cap.
func capDocstring(s string) string {
	if len(s) <= docstringMaxBytes {
		return s
	}
	cut := docstringMaxBytes - len(docstringTruncMarker)
	for cut > 0 && !utf8.RuneStart(s[cut]) {
		cut--
	}
	return s[:cut] + docstringTruncMarker
}

// snippetForLine returns the trimmed content of the given 1-indexed
// line, capped at snippetMaxBytes. Missing / out-of-range lines
// return "". No unicode-aware slicing: the cap is a byte budget, and
// tree-sitter-extracted line numbers are always in the input so the
// range walk terminates.
func snippetForLine(source []byte, line int) string {
	if line <= 0 {
		return ""
	}
	start := 0
	current := 1
	for i := 0; i < len(source) && current < line; i++ {
		if source[i] == '\n' {
			current++
			start = i + 1
		}
	}
	if current < line {
		return ""
	}
	end := start
	for end < len(source) && source[end] != '\n' {
		end++
	}
	s := strings.TrimSpace(string(source[start:end]))
	if len(s) > snippetMaxBytes {
		s = s[:snippetMaxBytes]
	}
	return s
}
